<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#00aa80"><meta name="description" content="JiMS — absensi kegiatan jamaah Jati Perhubungan."><title>Absen · JiMS</title><meta name="csrf-token" content="{{ csrf_token() }}"><link rel="manifest" href="/manifest.webmanifest"><link rel="apple-touch-icon" href="/icons/icon-192.png">@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="booting"><div id="boot-status" role="status">Memuat JiMS…</div><section id="login-screen" class="login-screen" hidden><form id="login-form" class="login-card panel"><img src="/assets/jims-logo.png" width="210" alt="JiMS"><h1>Selamat datang</h1><p class="muted">Masuk untuk melihat agenda dan mencatat kehadiran.</p><label>Email<input name="email" type="email" autocomplete="username" required autofocus></label><label>Kata sandi<input name="password" type="password" autocomplete="current-password" required></label><p id="login-error" class="form-error" role="alert"></p><button class="primary-button" type="submit">Masuk</button><small>Hubungi pengurus jika Anda belum memiliki akun.</small></form></section><div id="app-shell" hidden>
<svg class="svg-library" xmlns="http://www.w3.org/2000/svg"><defs>
<symbol id="qr-demo" viewBox="0 0 80 80"><path d="M4 4h22v22H4ZM54 4h22v22H54ZM4 54h22v22H4ZM11 11h8v8h-8ZM61 11h8v8h-8ZM11 61h8v8h-8ZM36 4v18m0 12h12v12H36ZM58 36h18M4 36h20m-12 9h12m12 14v17m10-18h12v18m10-26v12h8"/><text x="40" y="53" text-anchor="middle" fill="currentColor" stroke="none" font-size="11" font-family="Arial">DEMO</text></symbol>
<symbol id="mosque" viewBox="0 0 24 24"><path d="M2 21h20M5 21V7L3 3 1 7v14M19 21V7l2-4 2 4v14M7 13h10v8H7ZM7 13c0-4 5-5 5-8 0 3 5 4 5 8M10 21v-4a2 2 0 0 1 4 0v4M12 3V1"/></symbol>
<symbol id="book" viewBox="0 0 24 24"><path d="M12 5v16M12 5C9 3 5 3 2 4v15c3-1 7-1 10 2 3-3 7-3 10-2V4c-3-1-7-1-10 1Z"/></symbol>
<symbol id="logo" viewBox="0 0 48 48"><path d="M5 43h38M11 43V24c0-8 13-10 13-18 0 8 13 10 13 18v19M20 43V31l4-5 4 5v12M24 6V2"/></symbol>
<symbol id="check" viewBox="0 0 24 24"><path d="m5 12 5 5L20 7"/></symbol><symbol id="circle-check" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="m7 12 3 3 7-7"/></symbol>
<symbol id="menu" viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h16"/></symbol><symbol id="pin" viewBox="0 0 24 24"><path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/></symbol><symbol id="calendar" viewBox="0 0 24 24"><rect x="4" y="5" width="16" height="16" rx="2"/><path d="M8 3v5m8-5v5M4 11h16"/></symbol><symbol id="clock" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></symbol><symbol id="moon" viewBox="0 0 24 24"><path d="M19.5 15.5A9 9 0 0 1 8.5 4 9 9 0 1 0 19.5 15.5Z"/><path d="m17 3 1 3 3 1-3 1-1 3-1-3-3-1 3-1Z"/></symbol><symbol id="users" viewBox="0 0 24 24"><circle cx="12" cy="7" r="4"/><path d="M5 21v-3a7 7 0 0 1 14 0v3M3 5a4 4 0 0 0 0 8M21 5a4 4 0 0 1 0 8M1 21v-3l2-3m20 6v-3l-2-3"/></symbol><symbol id="screen" viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="13" rx="1"/><path d="M12 16v5m-5 0h10"/></symbol><symbol id="walk" viewBox="0 0 24 24"><circle cx="14" cy="4" r="2"/><path d="m10 13 2-6 4 5 4 1M12 8 7 10l-2 5m6-2 4 4 2 6m-7-10-1 5-5 5"/></symbol><symbol id="search" viewBox="0 0 24 24"><circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/></symbol><symbol id="filter" viewBox="0 0 24 24"><path d="M3 4h18l-7 9v6l-4 2v-8Z"/></symbol><symbol id="chevron" viewBox="0 0 24 24"><path d="m9 4 8 8-8 8"/></symbol><symbol id="history" viewBox="0 0 24 24"><path d="M3 11a9 9 0 1 1 2 7M1 6l2 6 5-3m4-3v7l4 3"/></symbol><symbol id="user" viewBox="0 0 24 24"><circle cx="12" cy="7" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/></symbol><symbol id="fingerprint-icon" viewBox="0 0 80 80"><path d="M17 23c13-16 33-16 46 0M13 37c2-29 52-29 54 0M21 50V36c0-24 38-24 38 0v12M13 48V37m54 11V37M29 55V36c0-14 22-14 22 0v16c0 8 5 14 11 18M21 42v9c0 9-3 15-8 19m27-36v19c0 15-5 21-10 26m-1-28c0 11-3 19-8 25m19-25c0 10 7 20 14 25M40 66l3 8"/></symbol>
</defs></svg>
<div class="sidebar-backdrop" id="backdrop"></div>
<aside class="sidebar" id="sidebar"><a class="brand" href="./" aria-label="JiMS beranda"><img class="brand-logo" src="assets/jims-logo.png" alt="JiMS — Jipi Management System" width="638" height="221"></a><nav aria-label="Navigasi utama"><button class="nav-item active" data-page="attendance"><svg><use href="#circle-check"/></svg>Absen</button><button class="nav-item" data-page="history"><svg><use href="#history"/></svg>Riwayat Absen</button></nav><div class="account"><div class="account-note"><span class="demo-dot"></span> <span id="connection-status">Menghubungkan…</span></div><button id="profile" class="profile"><span class="avatar mint">AF</span><strong id="profile-name">Alex</strong><svg><use href="#user"/></svg></button></div></aside>
<main><header class="page-header"><div class="mobile-header"><button class="icon-button" id="menu-button" aria-label="Buka navigasi" aria-expanded="false"><svg><use href="#menu"/></svg></button><a class="brand" href="./"><img class="brand-logo" src="assets/jims-logo.png" alt="JiMS — Jipi Management System" width="638" height="221"></a></div><div class="skyline" aria-hidden="true"></div><h1 id="page-title">Absen</h1><p id="page-description">Pilih kegiatan, lalu klik untuk absensi.</p></header>
<section id="attendance-page"><div class="event-list" id="events" aria-label="Pilih kegiatan"></div><div class="event-toolbar"><div id="event-dots" class="event-dots" aria-hidden="true"></div><button class="create-button" id="create-event"><span>＋</span> Buat Kegiatan Baru</button></div><p id="select-prompt" class="empty-events">Pilih kegiatan dan lokasi untuk mulai absen.</p><div class="workspace" hidden><section class="attendance-panel panel"><div class="selected-heading"><p>Absen untuk kegiatan :</p><h2 id="selected-event"></h2></div><div class="attendance-control" id="swipe-control"><button class="attendance-choice offline" data-attend="offline"><svg><use href="#mosque"/></svg><strong>Hadir Offline</strong><small class="desktop-hint">Geser ke kiri</small><small class="mobile-hint">Geser ke kiri</small></button><button class="fingerprint" id="fingerprint" aria-label="Absen hadir offline"><svg><use href="#fingerprint-icon"/></svg></button><button class="attendance-choice online" data-attend="online"><svg><use href="#screen"/></svg><strong>Izin / Hadir Online</strong><small class="desktop-hint">Geser ke kanan</small><small class="mobile-hint">Geser ke kanan</small></button></div><p class="attendance-feedback" id="attendance-feedback" aria-live="polite"></p><button class="other-button" id="other-attendance"><svg><use href="#users"/></svg><strong>Absenkan jamaah lain</strong><svg><use href="#chevron"/></svg></button></section><section class="people-panel panel"><div class="section-heading"><h2>Yang sudah absen</h2><span id="people-count"></span></div><div class="search-row"><label class="search"><svg><use href="#search"/></svg><input id="people-search" type="search" placeholder="Cari nama jamaah..." aria-label="Cari nama jamaah"></label><button class="icon-button filter-button" id="filter-button" aria-label="Filter status absensi" aria-expanded="false"><svg><use href="#filter"/></svg></button></div><div class="filter-options" id="filter-options" hidden><label>Tampilkan <select id="status-filter"><option value="all">Semua status</option><option value="offline">Hadir offline</option><option value="online">Hadir online</option><option value="izin">Izin</option></select></label></div><ul class="people-list" id="people"></ul></section></div></section>
<section id="history-page" class="panel history-panel" hidden><h2>Riwayat absensi Anda</h2><p class="muted">Riwayat kehadiran tersimpan di akun Anda.</p><ul id="history-list" class="people-list"></ul></section><section id="schedule-page" class="feature-page panel" hidden></section><section id="donations-page" class="feature-page" hidden></section><section id="classes-page" class="feature-page panel" hidden></section><section id="users-page" class="feature-page panel" hidden></section><section id="notifications-page" class="feature-page panel" hidden></section><section id="audit-page" class="feature-page panel" hidden></section><footer>JiMS <span>·</span> Jati Perhubungan</footer></main><nav class="mobile-bottom-nav" aria-label="Navigasi utama mobile"></nav></div>
<dialog id="dialog"><form id="dialog-form"><div class="dialog-heading"><h2 id="dialog-title"></h2><button type="button" id="close-dialog" class="close-button" aria-label="Tutup">×</button></div><div id="dialog-fields"></div><div class="dialog-actions"><button type="button" id="cancel-dialog" class="secondary-button">Batal</button><button class="primary-button" type="submit">Simpan</button></div></form></dialog><div class="toast" id="toast" role="status"></div>
</body></html>
